name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
  env:
    MIX_ENV: test
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: 22.2.6
        elixir-version: 1.10.1
    - uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - run: mix deps.get
    - run: mix test

